<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="DESKTOP-285KDFR" failures="3" tests="3" name="Sprint1(failed)" time="0.134" errors="0" timestamp="2022-10-10T21:23:01 IST">
  <testcase classname="rerunTestCases.TestCases2" name="loginMyntra" time="0.016">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at rerunTestCases.TestCases2.loginMyntra(TestCases2.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- loginMyntra -->
  <testcase classname="rerunTestCases.TestCases2" name="loginAmazon" time="0.0">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at rerunTestCases.TestCases2.loginAmazon(TestCases2.java:10)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- loginAmazon -->
  <testcase classname="rerunTestCases.TestCases" name="loginWhatsApp" time="0.007">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at rerunTestCases.TestCases.loginWhatsApp(TestCases.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- loginWhatsApp -->
  <testcase classname="rerunTestCases.TestCases" name="loginFB" time="0.0">
    <ignored/>
  </testcase> <!-- loginFB -->
  <testcase classname="rerunTestCases.TestCases2" name="loginFlipkart" time="0.0">
    <ignored/>
  </testcase> <!-- loginFlipkart -->
  <testcase classname="rerunTestCases.TestCases" name="loginTwitter" time="0.0">
    <ignored/>
  </testcase> <!-- loginTwitter -->
</testsuite> <!-- Sprint1(failed) -->
